config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :movies do
    resources :reviews#, shallow: true
  end

  resources :reviews

  root 'welcome#index'
  get "about" => "pages#about"

end

app/models/movie.rb
class Movie < ActiveRecord::Base

  has_many :reviews, dependent: :destroy

  validates :title, presence: :true
  validates :poster, presence: :true
  validates :rotten_tomatoes_score, presence: :true
  validates :genre, presence: :true
end

app/models/review.rb
class Review < ActiveRecord::Base

  belongs_to :movie
  belongs_to :user

  validates :title, presence: :true
  validates :body, presence: :true
  #validates :rating, presence: :true
  validates :recommendation, presence: :true
  validates :spoiler, :inclusion => {:in => [true, false]}

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :reviews
  has_many :movies, through: :reviews, source: :movie

  validates :name, presence: :true, case_sensitive: false

  # Virtual attribute for authenticating by either name or email
  # This is in addition to a real persisted field like 'name'
  attr_accessor :login

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(name) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      if conditions[:name].nil?
        where(conditions).first
      else
        where(name: conditions[:name]).first
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation, :remember_me) }
      devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :name, :email, :password, :remember_me) }
      devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :password_confirmation, :current_password) }
    end


end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update, :destroy]

  def index
    @movies = Movie.all
  end

  def new
    @movie = Movie.new
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def create
    @movie = Movie.new(movie_params)

    if @movie.save
      flash[:notice] = 'Movie successfully created.'
      redirect_to movie_path(@movie)
    else
      render :new
    end
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:id])

    if @movie.update_attributes(movie_params)
      flash[:notice] = 'Movie successfully updated.'
      redirect_to movie_path(@movie)
    else
      render :edit
    end
  end

  def destroy
    Movie.find(params[:id]).destroy
    flash[:notice] = 'Movie successfully deleted.'
    redirect_to movies_path
  end

  private

    def set_movie
      @movie = Movie.find(params[:id])
    end

    def movie_params
      params.require(:movie).permit(:title, :poster, :rotten_tomatoes_score, :genre)
    end

    def correct_user
      @movie = current_user.movies.find_by(id: params[:id])
      redirect_to movies_path, notice: "Not authorized to edit this movie" if @movie.nil?
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update, :destroy]

  def index
    @reviews = Review.all
  end

  def new
    @movie = Movie.find(params[:movie_id])
    @review = Review.new
  end

  def create
    @movie = Movie.find(params[:movie_id])
    @review = @movie.reviews.create(review_params)
    @review.user = current_user



    if @review.save
      flash[:notice] = 'Review successfully created.'
      redirect_to movie_path(@movie)
    else
      flash[:notice] = 'Review not successfully created.'
      render :new
    end
  end

  def show
    @movie = Movie.find(params[:movie_id])
    @review = Review.find(params[:id])
  end

  def edit
    @movie = Movie.find(params[:movie_id])
    review = @movie.reviews.create(review_params)
  end

  def update
    @movie = Movie.find(params[:id])
    @review = @movie.reviews.create(review_params)

    if @review.save(movie_params)
      flash[:notice] = 'Movie successfully updated.'
      redirect_to movie_review_path(@movie)
    else
      flash[:notice] = 'Movie not successfully updated.'
      render :edit
    end
  end

  def destroy
    @movie = Movie.find(params[:movie_id])
    @review = @movie.reviews.find(params[:id])
    @review.destroy
    redirect_to movie_path(@movie)
  end

  private

  def set_review
    @review = Review.find(params[:id])
  end

  def review_params
    params.require(:review).permit(:title, :body, :rating, :recommendation, :spoiler)
  end

  def correct_user
    @review = current_user.reviews.find_by(id: params[:id])
    redirect_to reviews_path, notice: "Not authorized to edit this review" if @review.nil?
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    if user_signed_in?
      redirect_to movies_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-brand">
        <%= link_to "WWWR", movies_path %>
      </div>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-collapse navbar-right">
        <% if user_signed_in? %>
        <li><%= link_to "Movies", movies_path %></li>
        <li><%= link_to 'Add Movie', new_movie_path %></li>
        <li><%= link_to "Reviews", reviews_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "RT", "http://www.rottentomatoes.com/", target: :_blank %></li>
        <li><%= link_to current_user.name, edit_user_registration_path %></li>
        <li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></li>
        <% else %>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <li><%= link_to "Sign In", new_user_session_path  %></li>

        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WeWatchWeReview</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/header' %>

  <div class = "container", class: "alert alert-info">
    <%= yield %>
  </div>

</body>
</html>

app/views/movies/_form.html.erb
<%= form_for @movie do |f| %>

  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :poster %>
  <%= f.text_field :poster %>

  <%= f.label :rotten_tomatoes_score, 'Rotten Tomatoes Score' %>
  <%= f.text_field :rotten_tomatoes_score %>


  <%= f.label :genre %>
  <%= f.text_field :genre %>

  <%= f.submit %>
<% end %>

app/views/movies/edit.html.erb
<h1>Edit Movie</h1>

<%= render 'form' %>

<%= button_to 'Delete Movie', movie_path(@movie), method: :delete, data: { confirm: 'Are you sure?' } %>

<%= link_to 'Back', movie_path %>

app/views/movies/index.html.erb
<%= flash[:notice] %>
<div class="panel-title">
  <h1>Movies Index</h1>
</div>


<div class="panel panel-default">
  <div class="panel-heading">
    <% @movies.each do |movie| %>
    <h3 class="panel-title"><%= movie.title %></h3>
  </div>
  <div class="panel-body">
      <p><%= link_to image_tag(movie.poster), movie %></p>
      <p><%= movie.rotten_tomatoes_score %></p>
      <p><%= movie.genre %></p>
    <% end %>
  </div>
</div>

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form' %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<div><%= link_to 'Back', movies_path %></div>
<div><%= link_to 'Edit', edit_movie_path %></div>
<div><%= link_to 'New Review', new_movie_review_path(@movie) %></div>
<%= flash[:notice] %>

<div class="panel panel-default">
  <div class="panel-heading">
    <div class="panel-title">
        <h1><%= @movie.title %></h1>
    </div>
  </div>
    <div class="panel-body">
      <div>
        <p><%= link_to image_tag(@movie.poster), @movie.poster %></p>
        <p><%= @movie.rotten_tomatoes_score %></p>
        <p><%= @movie.genre %></p>


      <h2>Reviews for this movie:</h2>
      <% @movie.reviews.each do |review| %>
        <p>
          <%= link_to review.title, movie_review_path(@movie, review) %> <%= review.user.name %>
        </p>
      <% end %>
      </div>
    </div>

</div>

app/views/pages/about.html.erb
<div class="panel-heading">
  <h1>About</h1>
</div>
<div class="form-group">
  <p>We Watch We Review is a movie review site intended to allow users to view reviews from their friends instead of critics or strangers online with no context to their personality.</p>
  <p>This was my first project in General Assembly's Web Development Immersive. The project is on hold until more features can be added.</p>
  <p>Upcoming features:
    <ul>
      <li>Connect to Rotten Tomatoes API to pull in data for each movie</li>
      <li>Add a search feature for movies that have not been reviewed yet</li>
      <li>Add friends</li>
      <li>Connect a front-end JavaScript framework</li>
      <li>Add better CSS than the standard Bootsrap colors :)</li>
    </ul>
  </p>
  <p>To be realistic, I will probably pick this back up after I am able to get a job because 1) this is a fun concept, 2) there are other projects I want to work on now until then and 3) I need to prepare for getting said job :)</p>
  <p>I apologize for Heroku not allowing the login page to work currently. If you're interested in checking out the code (and upcoming features) on Github, you can find it here: <a href='https://github.com/goodeats/wewatchwereview'>WeWatchWeReview</a> or visit my personal website at <a href='http://www.patneedham.me'>www.patneedham.me</a>. Thanks!</p>
</div>

app/views/reviews/_form.html.erb
<%= form_for([@movie, @movie.reviews.build]) do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <div class="form-group">
    <%= f.label :body %><br>
    <%= f.text_area :body, class: "form-control", rows: '3', placeholder: "Write your review here" %>
  </div>



  <div class="" data-toggle="buttons-radio">
    <%= f.label :rating %><br>
    <%= f.radio_button :rating, '1', :id=>"first" %>
    <label for="first" class="">1</label>

    <%= f.radio_button :rating, '2', :id=>"second" %>
    <label for="second" class="">2</label>

    <%= f.radio_button :rating, '3', :id=>"third" %>
    <label for="third" class="">3</label>

    <%= f.radio_button :rating, '4', :id=>"fourth" %>
    <label for="fourth" class="">4</label>

    <%= f.radio_button :rating, '5', :id=>"fifth" %>
    <label for="fifth" class="">5</label>
  </div>



  <p>
    <%= f.label "See this movie if:" %><br>
    <%= f.text_area :recommendation %>
  </p>
  <p>
    <%= f.label :spoiler %><br>
    <%= f.check_box :spoiler, value: true %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/reviews/_reviews.html.erb
<p>
  <strong>Title:</strong>
  <%= review.title %>
</p>

<p>
  <strong>Review:</strong>
  <%= review.body %>
</p>

<p>
  <strong>Rating:</strong>
  <%= review.rating %>
</p>

<p>
  <strong>Recommendation:</strong>
  <%= review.recommendation %>
</p>

<p>
  <strong>Spoiler Warning:</strong>
  <%= review.spoiler %>
</p>

<p>
  <%= link_to 'Destroy Review', [review.movie, review],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/reviews/edit.html.erb
<h1>Edit Review</h1>

<%= render 'form' %>

<%= link_to 'Back', movie_path %>

app/views/reviews/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <div class="panel-title">
      <h1>Movie Reviews</h1>
    </div>
  </div>
  <div class="panel-body">
    <% @reviews.each do |review| %>
      <div>
        <ul>
          <li><%= link_to review.title, review_path(review.id) %></li>
        </ul>
      </div>
    <% end %>

  </div>
</div>

app/views/reviews/new.html.erb
<h1><%= @movie.title %></h1>
<h2>New Review</h2>

<%= render 'form' %>

<%= link_to 'Back', movie_path(@movie.id) %>

app/views/reviews/show.html.erb
<div><%= link_to 'Back', movie_path(@movie.id) %></div>
<div><%= link_to 'New Review', new_movie_review_path(@movie) %></div>

<% if @review.user == current_user %>
  <div><%= link_to 'Edit', edit_movie_review_path(@movie, @review) %></div>
  <%= button_to 'Delete Review', movie_review_path(@movie, @review), method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>


<h1>Show this review here</h1>

<%= flash[:notice] %>
<div class = "row">
  <div class="col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading center">
        <h2><%= @review.title %></h2>
      </div>
      <div class="panel-body">
        <h3><%= @review.user.name %></h3>
        <p><%= @review.body %></p>
        <p><%= @review.rating %></p>
        <p><%= @review.recommendation %></p>
        <p><%= @review.spoiler %></p>
      </div>
    </div>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(object.errors.count, "error") %> prohibited this object from being saved:</h2>

  <ul>
    <% object.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/welcome/index.html.erb
<div class="jumbotron center">
  <h2>Welcome to</h2>
  <h1>We Watch/We Review!!!</h1>
  <p>
    <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
    <%= link_to "Log In", new_user_session_path, class: "btn btn-default btn-lg" %>
  </p>
</div>